language: php
php:
    - 5.5
script: php run testrun create name=models/country
before_script:
    - mysql -e 'create database endofcodes_test;'
    - cd database/migration
    - for i in `find .|grep -v ^.$|grep -v migrate.php`; do ENVIRONMENT=test DB_NAME=travis DB_PASSWORD='' php $i; done
    - cd ../..
